config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq-status/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  namespace :checking_account do
    resources :home, only: %i[index]
    resources :cashboxes, only: :index
    resources :consolidations, only: :index
  end

  namespace :audits do
    get "user", to: "users#index"
    get "user/:id", to: "users#show", as: "user_audit"
  end

  resources :bank_accounts
  resources :payment_methods
  resources :discount_authorizations, only: %i[index show update]

  namespace :ventas do
    resources :listado_de_precio_archivos
    resources :listado_de_precios, only: %i[index]
    resources :home, only: %i[index]
    resources :control_units, only: %i[index] do
      resources :quotations, module: "control_units"
    end
    resources :quotations, module: "control_units" do
      member do
        get "pdf", to: "quotations#pdf", as: :pdf
      end
      get "send_email_pdf/:quotation_id", to: "quotations#send_email_pdf", as: :send_email_pdf, on: :collection
    end

    get "calculator", to: "control_units/quotations#calculator", as: :calculator

    resources :reserves
  end

  resources :control_unit_types
  resources :control_unit_sub_types do
    scope module: :control_unit_sub_types do
      resources :control_unit_sub_type_projects, only: %i[index]
    end
  end
  resources :control_unit_sub_type_projects, only: %i[show update] do
    scope module: :control_unit_sub_type_projects do
      resources :extras, only: %i[index new create]
    end
  end
  resources :extras, only: %i[index show new edit create update destroy]
  get "control_unit_settings/subtypes", to: "control_unit_settings#subtypes", as: :subtypes

  resources :boundaries, only: %i[show edit update destroy]
  resources :country_settings, only: %i[index]
  resource :country_settings, only: %i[update]
  get "country_settings/subdivisions", to: "country_settings#subdivisions", as: :subdivisions
  get "country_settings/cities", to: "country_settings#cities", as: :cities
  get "projects/:project_id/control_units/export_template", to: "projects/control_units#export_template",
    as: :export_template_control_units
  resources :control_units, only: %i[show edit update destroy] do
    get "versions", on: :member
    member do
      put "boundaries", to: "control_units/boundaries#update"
    end
    collection do
      get :export_form
      post :export
    end
    resources :boundaries, shallow: true, only: %i[new index], module: :control_units
  end
  resources :projects do
    collection do
      get :export_form
      post :export
    end
    member do
      put "fincas", to: "projects/fincas#update"
    end
    resources :control_units, shallow: true, only: %i[new create index], module: :projects
    resources :fincas, shallow: true, only: %i[new index], module: :projects

    post "control_units/import_create", to: "projects/control_units#import_create", as: :import_create_control_units
    post "control_units/import_update", to: "projects/control_units#import_update", as: :import_update_control_units
  end
  resources :clients

  scope :configurations do
    # get '/', to: 'configurations#home', as: :configurations
    resources :users do
      get "versions", on: :member
    end
    resources :control_unit_statuses
    resources :roles do
      resources :permissions, shallow: true, only: %i[new create index], module: :roles
    end
    resources :financial_entities
    resources :sale_request_templates do
      get "/preview", to: "sale_request_templates#preview", as: :preview, on: :member
    end
  end
  namespace :configurations do
    resources :tipo_de_identificacion_clientes
  end
  # resources :users
  # resources :control_units do
  #   resources :boundaries
  # end
  devise_for :users, controllers: {
    sessions: "users/sessions"
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check
  root to: "home#index"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/control_unit_types_controller.rb
# frozen_string_literal: true

class ControlUnitTypesController < ApplicationController
  before_action :set_control_unit_type, only: %i[show edit update destroy versions]

  def index
    @control_unit_types = ControlUnitType.all
  end

  def show
  end

  def new
    @control_unit_type = ControlUnitType.new
  end

  def edit
  end

  def create
    @control_unit_type = ControlUnitType.new(control_unit_type_params)

    respond_to do |format|
      if @control_unit_type.save
        format.html do
          redirect_to control_unit_type_url(@control_unit_type), notice: "El tipo fue creado exitosamente."
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @control_unit_type.update(control_unit_type_params)
        format.html do
          redirect_to control_unit_type_url(@control_unit_type), notice: "El tipo se actualizó exitosamente."
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @control_unit_type.destroy
        format.html { redirect_to control_unit_types_url, notice: "El tipo  fue eliminado con éxito." }
      else
        # flash[:alert] = 'No se puede eliminar el rol porque tiene usuarios asociados'
        format.html do
          redirect_to control_unit_types_url,
            alert: "El tipo #{@control_unit_type.name} no se puede eliminar porque tiene subtipos asociados"
        end
      end
    end
  end

  def versions
  end

  private

  def set_control_unit_type
    @control_unit_type = ControlUnitType.find(params[:id])
  end

  def control_unit_type_params
    params.require(:control_unit_type).permit(:name)
  end
end

app/views/control_unit_types/_control_unit_type.html.erb
<div id="<%= dom_id(control_unit_type) %>" class="<%= form_details_class %>">
  <p class="<%= p_class %>">
    <strong>Nombre:</strong>
    <%= control_unit_type.name %>
  </p>

</div>

app/views/control_unit_types/_form.html.erb
<%= form_with(model: control_unit_type, class: form_class, data:{controller: "form-protection"}) do |form| %>
  <% if control_unit_type.errors.any? %>
    <div class=<%= div_error_class %>>
      <h2><%= pluralize(control_unit_type.errors.count, "error") %> para guardar este tipo:</h2>
      <ul>
        <% control_unit_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class=<%= div_field_form_class %>>
    <%= form_label(form, :name) %>
    <%= form.text_field :name, class: field_class %>
  </div>

  <div>
    <%= form.submit class: [submit_class, "submitButton"] %>
  </div>
<% end %>

app/views/control_unit_types/edit.html.erb
<section class="<%= section_class %>">
  <div class="<%= div_edit_class %>">
  <h1 class="<%= h1_edit_class %>">Editando tipo</h1>

  <%= render "form" , control_unit_type: @control_unit_type %>

    <br>

    <div class="<%= div_links_edit_class %>">
      <%= link_to "Mostrar este tipo" , @control_unit_type, class: link_edit_class %>
      <span>|</span>
      <%= link_to "Regresar a tipo" , control_unit_types_path, class: link_edit_class %>
    </div>
  </div>
</section>

app/views/control_unit_types/index.html.erb
<section class="bg-white dark:bg-gray-900">
  <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
    <h1 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Tipos de unidad de control</h1>
    <%= link_to "Nuevo tipo", new_control_unit_type_path, class: link_index_helper %>

    <br>
    <div class="<%= div_table_class %>">
      <table class="<%= table_class %>">
        <thead class="<%= thead_class %>">
          <tr>
            <th scope="col" class="<%= th_td_class %>">Nombre</th>
            <th scope="col" class="<%= th_td_class %>">Fecha de creación</th>
            <th scope="col" class="<%= th_td_class %>">Fecha de actualización</th>

            <!-- Más columnas según sea necesario -->
            <th scope="col" class="<%= th_td_class %>"> Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @control_unit_types.each do |control_unit_type| %>
            <tr class="<%= tr_class %>">
              <td class="<%= th_td_class %>"><%= control_unit_type.name %></td>
              <td class="<%= th_td_class %>"><%= l(control_unit_type.created_at, format: :short) %></td>
              <td class="<%= th_td_class %>"><%= l(control_unit_type.updated_at, format: :short) %></td>
              <td class="<%= th_td_class %>">
                <div class="flex space-x-2">
                <%= link_to control_unit_type do %>
                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <path stroke="currentColor" stroke-width="2" d="M21 12c0 1.2-4 6-9 6s-9-4.8-9-6c0-1.2 4-6 9-6s9 4.8 9 6Z" />
                  <path stroke="currentColor" stroke-width="2" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                </svg>
              <% end %>

                <%= link_to edit_control_unit_type_path(control_unit_type) do %>
                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m10.8 17.8-6.4 2.1 2.1-6.4m4.3 4.3L19 9a3 3 0 0 0-4-4l-8.4 8.6m4.3 4.3-4.3-4.3m2.1 2.1L15 9.1m-2.1-2 4.2 4.2" />
                </svg>
                <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/control_unit_types/new.html.erb
<section class="bg-white dark:bg-gray-900">
  <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
    <h1 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Nuevo Tipo</h1>

    <%= render "form", control_unit_type: @control_unit_type %>

    <div class="mt-6">
      <%= link_to "Regresar a tipos", control_unit_types_path, class: "text-primary-700 hover:text-primary-900 dark:text-primary-500 dark:hover:text-primary-700" %>
    </div>
  </div>
</section>

app/views/control_unit_types/show.html.erb
<section class="bg-gray-50 dark:bg-gray-900 p-3 sm:p-5">
  <h1 class="text-6xl mb-4 text-xl font-bold text-gray-900 dark:text-white"><%= @control_unit_type.name %></h1>

  <div class="py-8 px-4 mx-auto max-w-2xl lg:py-2">

    <%= render @control_unit_type %>

    <div class="flex items-center justify-start space-x-4 mt-6">
      <%= link_to "Editar este tipo", edit_control_unit_type_path(@control_unit_type), class: "text-primary-700 hover:text-primary-900 dark:text-primary-500 dark:hover:text-primary-700" %>
      <span>|</span>
      <%= link_to "Regresar a tipos", control_unit_types_path, class: "text-primary-700 hover:text-primary-900 dark:text-primary-500 dark:hover:text-primary-700" %>
    </div>
    <div class="mt-4">
      <%= button_to "Eliminar este tipo", @control_unit_type, method: :delete, form: { data: { turbo_confirm: '¿Estás seguro?' } }, class: "text-white bg-red-600 hover:bg-red-700 focus:ring-4 focus:ring-red-200 dark:focus:ring-red-900 font-medium rounded-lg text-sm px-5 py-2.5 text-center" %>
    </div>
  </div>
</section>