config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq-status/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  namespace :checking_account do
    resources :home, only: %i[index]
    resources :cashboxes, only: :index
    resources :consolidations, only: :index
  end

  namespace :audits do
    get "user", to: "users#index"
    get "user/:id", to: "users#show", as: "user_audit"
  end

  resources :bank_accounts
  resources :payment_methods
  resources :discount_authorizations, only: %i[index show update]

  namespace :ventas do
    resources :listado_de_precio_archivos
    resources :listado_de_precios, only: %i[index]
    resources :home, only: %i[index]
    resources :control_units, only: %i[index] do
      resources :quotations, module: "control_units"
    end
    resources :quotations, module: "control_units" do
      member do
        get "pdf", to: "quotations#pdf", as: :pdf
      end
      get "send_email_pdf/:quotation_id", to: "quotations#send_email_pdf", as: :send_email_pdf, on: :collection
    end

    get "calculator", to: "control_units/quotations#calculator", as: :calculator

    resources :reserves
  end

  resources :control_unit_types
  resources :control_unit_sub_types do
    scope module: :control_unit_sub_types do
      resources :control_unit_sub_type_projects, only: %i[index]
    end
  end
  resources :control_unit_sub_type_projects, only: %i[show update] do
    scope module: :control_unit_sub_type_projects do
      resources :extras, only: %i[index new create]
    end
  end
  resources :extras, only: %i[index show new edit create update destroy]
  get "control_unit_settings/subtypes", to: "control_unit_settings#subtypes", as: :subtypes

  resources :boundaries, only: %i[show edit update destroy]
  resources :country_settings, only: %i[index]
  resource :country_settings, only: %i[update]
  get "country_settings/subdivisions", to: "country_settings#subdivisions", as: :subdivisions
  get "country_settings/cities", to: "country_settings#cities", as: :cities
  get "projects/:project_id/control_units/export_template", to: "projects/control_units#export_template",
    as: :export_template_control_units
  resources :control_units, only: %i[show edit update destroy] do
    get "versions", on: :member
    member do
      put "boundaries", to: "control_units/boundaries#update"
    end
    collection do
      get :export_form
      post :export
    end
    resources :boundaries, shallow: true, only: %i[new index], module: :control_units
  end
  resources :projects do
    collection do
      get :export_form
      post :export
    end
    member do
      put "fincas", to: "projects/fincas#update"
    end
    resources :control_units, shallow: true, only: %i[new create index], module: :projects
    resources :fincas, shallow: true, only: %i[new index], module: :projects

    post "control_units/import_create", to: "projects/control_units#import_create", as: :import_create_control_units
    post "control_units/import_update", to: "projects/control_units#import_update", as: :import_update_control_units
  end
  resources :clients

  scope :configurations do
    # get '/', to: 'configurations#home', as: :configurations
    resources :users do
      get "versions", on: :member
    end
    resources :control_unit_statuses
    resources :roles do
      resources :permissions, shallow: true, only: %i[new create index], module: :roles
    end
    resources :financial_entities
    resources :sale_request_templates do
      get "/preview", to: "sale_request_templates#preview", as: :preview, on: :member
    end
  end
  namespace :configurations do
    resources :tipo_de_identificacion_clientes
  end
  # resources :users
  # resources :control_units do
  #   resources :boundaries
  # end
  devise_for :users, controllers: {
    sessions: "users/sessions"
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check
  root to: "home#index"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/ventas/control_units/quotations_controller.rb
# frozen_string_literal: true

module Ventas
  module ControlUnits
    class QuotationsController < ApplicationController
      include ActiveStorage::SetCurrent

      before_action :get_clients_info, only: %i[new edit]
      before_action :set_quotation, only: %i[show edit update destroy pdf]
      before_action :set_quotation_params, only: %i[show edit pdf]
      before_action :set_show_info, only: %i[show]
      before_action :set_max_allowed_discount_percentage, only: %i[new edit]
      before_action :set_query_params, only: %i[index]
      after_action :check_discount_authorization, only: %i[create update]
      after_action :set_pdf_update_at, only: %i[pdf]

      def index
        @headers = [
          {name: "No. de Cotización", field: "reference_number", sortable: true},
          {name: "Nombre Cliente", field: "client_name", sortable: true},
          {name: "Fecha de Creación", field: "created_at", sortable: true},
          {name: "Fecha de Actualización", field: "updated_at", sortable: true}
        ]

        @q = Quotation.all.ransack(params[:q])
        @quotations = @q.result

        @pagy, @quotations = process_query_params(@quotations)
      end

      def show
        respond_to do |format|
          format.html
          format.pdf do
            render pdf: "Cotización_#{@quotation.client_name}_#{@quotation.created_at.strftime("%d-%m-%Y")}",
              template: "ventas/control_units/quotations/show_pdf", formats: [:html]
          end
        end
      end

      def new
        @quotation = Quotation.new(quotation_params: {control_units: []}.to_json)
        @financial_entities = FinancialEntity.all
        @control_unit_codes = params[:control_unit_codes] || []
        @control_units_months_to_cession_hash = {}
        @control_units_extras_hash = {}
        @control_units_custom_payments_hash = {}
        @control_units_custom_down_payment_hash = {}
        @custom_house = params[:custom_house]

        set_control_units

        return unless @custom_house.present?

        project_id = nil
        custom_house = JSON.parse(@custom_house)
        price = custom_house["price"].to_f
        price_dollar = custom_house["price_dollar"].to_f
        custom_house_lots = custom_house["lots"].map do |lot_code|
          control_unit = ControlUnit.find_by(code: lot_code)
          project_id = control_unit.project.id if project_id.nil?
          price += control_unit.precio_de_lista.to_f
          price_dollar += control_unit.precio_de_lista_dollar.to_f
          {
            code: control_unit.code
          }
        end

        # Esto debe ajustarse para que tome los extras del proyecto y tipo de la casa customizada.
        extras = get_extras_for_custom_house_id(custom_house["subtype_project_hash"].values.first, project_id)

        @control_units << {
          id: custom_house["name"],
          code: custom_house["name"],
          price:,
          price_dollar:,
          lots: custom_house_lots,
          extras: custom_house["types"].each_with_object({}) do |type, hash|
            hash[type] = extras[type].map do |extra|
              {
                id: extra.id,
                name: extra.name,
                price: extra.precio.to_f,
                price_dollar: extra.precio_dollar.to_f,
                apply: false,
                quantity: 1
              }
            end
          end,
          types: custom_house["types"],
          subtype_project_hash: custom_house["subtype_project_hash"],
          is_custom_house: true
        }

        @control_unit_codes << custom_house["name"]
      end

      def create
        @quotation = Quotation.new(quotation_params)
        respond_to do |format|
          if @quotation.save
            format.html do
              redirect_to ventas_quotation_url(@quotation), notice: "La cotización fue creada exitosamente.", turbolinks: true
            end
          else
            format.html { render :new, status: :unprocessable_entity }
          end
        end
      end

      def edit
        @financial_entities = FinancialEntity.all
      end

      def update
        respond_to do |format|
          if @quotation.update(quotation_params)
            @quotation.purge_pdf
            format.html do
              redirect_to ventas_quotation_url(@quotation), notice: "La cotización fue actualizada exitosamente.", turbolinks: true
            end
          else
            format.html { render :edit, status: :unprocessable_entity }
          end
        end
      end

      def destroy
        respond_to do |format|
          if @quotation.destroy
            format.html { redirect_to ventas_quotations_url, notice: "La cotización fue eliminada con éxito." }
            format.json { head :no_content }
          else
            format.html do
              redirect_to ventas_quotations_url,
                alert: "La cotización no se puede eliminar."
            end
          end
        end
      end

      def calculator
        @quotation = Quotation.new
        @financial_entities = FinancialEntity.all
        @calculator_only = true
      end

      def pdf
        @quotation.generate_pdf

        respond_to do |format|
          format.html
          format.pdf do
            redirect_to @quotation.pdf.url, allow_other_host: true
          end
        end
      rescue => e
        Rails.logger.error("Error generating PDF: #{e.message} #{e.backtrace}")
        Rollbar.error(e, "Error generating PDF: #{e.message}", {quotation_id: @quotation.id})
        redirect_to ventas_quotations_url(@quotation),
          alert: "Ocurrio un error al generar el PDF. Contacte a soporte indicando el error y el No. de Cotizacion ##{@quotation.reference_number}"
      end

      def send_email_pdf
        quotation = Quotation.find(params[:quotation_id])

        QuotationMailer.send_quotation_email(quotation).deliver_now

        redirect_back(fallback_location: ventas_quotations_url, notice: "La cotización fue enviada exitosamente.")
      rescue => e
        redirect_back(fallback_location: ventas_quotations_url, alert: "Error al enviar la cotización: #{e.message}")
      end

      private

      def get_clients_info
        @clients = Client.select(:id, :tipo_de_cliente, :nombres, :apellidos, :dpi, :denominacion_nombre_comercial, :nit, :teléfono_celular, :correo_electrónico).order(id: :asc)
        @clients = @clients.map do |client|
          display_text = if client.tipo_de_cliente == "Jurídico"
            client.nit.present? ? "#{client.denominacion_nombre_comercial} - #{client.nit}" : client.denominacion_nombre_comercial
          else
            client.dpi.present? ? "#{client.nombres} #{client.apellidos} - #{client.dpi}" : "#{client.nombres} #{client.apellidos}"
          end
          client.attributes.merge(display_text: display_text)
        end
      end

      def set_show_info
        @quotation_params = quotation_parsed_params
        set_control_units
        check_custom_house(@quotation_params)
        set_extras_break_down
        set_control_units_break_down
        set_lots_break_down
        set_custom_payments_break_down
      end

      def set_quotation
        @quotation = Quotation.find(params[:id])
      end

      def set_control_unit
        @control_unit = ControlUnit.find(params[:control_unit_id])
      end

      def quotation_params
        params.require(:quotation).permit(:client_id, :client_name, :client_phone, :client_email, :quotation_params,
          :down_payment_months)
      end

      def pdf_filename
        "#{@quotation.reference_number}_#{Time.now.strftime("%Y-%m-%d %H:%M:%S")}"
      end

      def set_quotation_params
        @parsed_quotation_params = quotation_parsed_params
        @control_unit_codes = @parsed_quotation_params["control_units"].map { |cu| cu["code"] }
        @control_units_extras_hash = @parsed_quotation_params["control_units"].each_with_object({}) do |cu, hash|
          hash[cu["id"]] = if cu["is_custom_house"]
            cu["types"].each_with_object({}) do |type, type_hash|
              type_hash[type] = cu["extras"][type].each_with_object({}) do |extra, extras_hash|
                extras_hash[extra["id"]] = {
                  "apply" => extra["apply"],
                  "quantity" => extra["quantity"] || 1
                }
              end
            end
          else
            cu["extras"].each_with_object({}) do |extra, extras_hash|
              extras_hash[extra["id"]] = {
                "apply" => extra["apply"],
                "quantity" => extra["quantity"] || 1
              }
            end
          end
        end
        @control_units_months_to_cession_hash = @parsed_quotation_params["control_units"].each_with_object({}) do |cu, hash|
          hash[cu["id"]] = cu["months_to_cession"] || 1
        end
        @control_units_custom_payments_hash = @parsed_quotation_params["control_units"].each_with_object({}) do |cu, hash|
          hash[cu["id"]] = cu["custom_payments"] || {}
        end
        @control_units_custom_down_payment_hash = @parsed_quotation_params["control_units"].each_with_object({}) do |cu, hash|
          hash[cu["id"]] = cu["custom_down_payment"] || {}
        end

        set_control_units
        check_custom_house(@parsed_quotation_params)
      end

      def set_control_units
        @control_units ||= ControlUnit.where(code: @control_unit_codes).map do |control_unit|
          {
            id: control_unit.id,
            code: control_unit.code,
            price: control_unit.precio_de_lista.to_f,
            price_dollar: control_unit.precio_de_lista_dollar.to_f,
            months_to_cession: @control_units_months_to_cession_hash[control_unit.id],
            extras: (Extra.for_project_and_control_unit_type(control_unit.project.id,
              control_unit.control_unit_type_id) + control_unit.extras).map do |extra|
                      {
                        id: extra.id,

app/controllers/ventas/home_controller.rb
# frozen_string_literal: true

module Ventas
  class HomeController < ApplicationController
    def index
    end
  end
end

app/controllers/ventas/listado_de_precio_archivos_controller.rb
# frozen_string_literal: true

module Ventas
  class ListadoDePrecioArchivosController < ApplicationController
    before_action :set_listado_de_precio_archivo, only: %i[show edit update destroy]

    def index
      @listado_de_precio_archivos = ListadoDePrecioArchivo.all
    end

    def new
      @listado_de_precio_archivo = ListadoDePrecioArchivo.new
    end

    def create
      @listado_de_precio_archivo = ListadoDePrecioArchivo.new(listado_de_precio_archivo_params)
      if @listado_de_precio_archivo.save
        ListadoDePrecioArchivos::Import.call(@listado_de_precio_archivo)
        redirect_to ventas_listado_de_precio_archivo_url(@listado_de_precio_archivo),
          notice: "El listado de precio fue creado exitosamente."
      else
        render :new
      end
    end

    def show
    end

    def edit
    end

    def update
      if @listado_de_precio_archivo.update(listado_de_precio_archivo_params)
        redirect_to ventas_listado_de_precio_archivo_url(@listado_de_precio_archivo),
          notice: "El listado de precio fue actualizado exitosamente."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @listado_de_precio_archivo.destroy
      redirect_to ventas_listado_de_precio_archivos_path, notice: "El listado de precio fue eliminado exitosamente."
    end

    private

    def set_listado_de_precio_archivo
      @listado_de_precio_archivo = ListadoDePrecioArchivo.find(params[:id])
    end

    def listado_de_precio_archivo_params
      params.require(:listado_de_precio_archivo).permit(:nombre, :fecha_de_listado, :archivo)
    end
  end
end

app/controllers/ventas/listado_de_precios_controller.rb
# frozen_string_literal: true

module Ventas
  class ListadoDePreciosController < ApplicationController
    # before_action :set_listado_de_precio, only: %i[show edit update destroy]

    def index
      search_params = params.permit(:page, :format,
        q: [:control_unit_code_cont])
      @q = ListadoDePrecio.ransack(params[:q])
      @query = search_params[:q]

      @pagy, @listado_de_precios = pagy_countless(@q.result.includes(:control_unit))
      # @listado_de_precios = ListadoDePrecio.all
    end

    # private
    # def set_listado_de_precio
    #   @listado_de_precio = ListadoDePrecio.find(params[:id])
    # end
  end
end

app/views/ventas/reserves/_form.html.erb
<%= form_with(model: [:ventas, @reserve], class: form_class, data: { controller: "form-protection", turbo: "false" }) do |form| %>
  <% if reserve.errors.any? %>
    <div class="<%= div_error_class %>">
      <h2><%= pluralize(reserve.errors.count, "error") %> para guardar esta reserva:</h2>
      <ul>
        <% reserve.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Dropdown for Quotation -->
  <div class="<%= div_field_form_class %>">
    <%= form_label(form, :quotation_id) %>
    <%= form.collection_select(
          :quotation_id,
          Quotation.all,               
          :id,                         
          :reference_number,           
          { prompt: "Seleccionar No. de cotización" },
          { class: field_class }
        ) %>
  </div>

  <!-- Dropdown for Client -->
  <div class="<%= div_field_form_class %>">
    <%= form_label(form, :client_id) %>
    <%= form.collection_select(
          :client_id,
          Client.all,                 
          :id,                         
          :nombre_completo,           
          { prompt: "Seleccionar cliente" },
          { class: field_class }
        ) %>
  </div>

  <div class="<%= div_field_form_class %>">
    <%= form_label(form, :quantity) %>
    <%= form.number_field :quantity, class: field_class, step: 1, min: 0 %>
  </div>

  <div class="<%= div_field_form_class %>">
    <%= form_label(form, :receipt_number) %>
    <%= form.number_field :receipt_number, class: field_class, step: 1, min: 0 %>
  </div>

  <div>
    <%= form.submit class: [submit_class, "submitButton"]  %>
  </div>
<% end %>

app/views/ventas/reserves/_reserve.html.erb
<div id="<%= dom_id(reserve) %>" class="<%= form_details_class %>">

  <p class="<%= p_class %>">
    <strong>Nombre del cliente:</strong>
    <%= reserve.client.nombre_completo %>
  </p>


  <p class="<%= p_class %>">
    <strong>No. de Cotización:</strong>
    <%= reserve.quotation.reference_number %>
  </p>

  <p class="<%= p_class %>">
    <strong>Codigo de unidad de control:</strong>
    <%= reserve.quotation.control_unit_object_code %>
  </p>

  <p class="<%= p_class %>">
    <strong>Vigente hasta:</strong>
    <%= (reserve.created_at + reserve.quotation.project.quotation_valid_days.days).strftime("%d/%m/%Y") %>
  </p>

  <p class="<%= p_class %>">
    <strong>Monto:</strong>
    <%= reserve.quantity %>
  </p>

  <p class="<%= p_class %>">
    <strong>No. de recibo:</strong>
    <%= reserve.receipt_number %>
  </p>

  <p class="<%= p_class %>">
    <strong>Vendedor:</strong>
    <%= reserve.user.name %>
  </p>

  <p class="<%= p_class %>">
    <strong>Fecha de creación:</strong>
    <%= l(reserve.created_at, format: :short) %>
    
  </p>
</div>

app/views/ventas/reserves/_table_actions.html.erb
<div class="flex space-x-2">
  <%= link_to ventas_reserve_url(reserve), data: { turbo_frame: "_top" } do %>
    <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
      <path stroke="currentColor" stroke-width="2" d="M21 12c0 1.2-4 6-9 6s-9-4.8-9-6c0-1.2 4-6 9-6s9 4.8 9 6Z"/>
      <path stroke="currentColor" stroke-width="2" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
    </svg>
  <% end %>

  <%= link_to edit_ventas_reserve_url(reserve), data: { turbo_frame: "_top" } do %>
    <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m10.8 17.8-6.4 2.1 2.1-6.4m4.3 4.3L19 9a3 3 0 0 0-4-4l-8.4 8.6m4.3 4.3-4.3-4.3m2.1 2.1L15 9.1m-2.1-2 4.2 4.2"/>
    </svg>
  <% end %>

  <%= button_to ventas_reserve_url(reserve), method: :delete, form: { data: { turbo: false, controller: "confirm", confirm_message_value: "¿Estás seguro?" }} do %>
    <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 7h14m-9 3v8m4-8v8M10 3h4a1 1 0 0 1 1 1v3H9V4a1 1 0 0 1 1-1ZM6 7h12v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7Z"/>
    </svg>
  <% end %>
</div>

app/views/ventas/reserves/_table_body.html.erb
<%
  reserve = row
%>

<tr class="<%= tr_class %>">
  <td class="<%= th_td_class %>">
      <%= reserve.reference_number %>
  </td>

  <td class="<%= th_td_class %>">
      <%= reserve.client.nombre_completo %>
  </td>

  <td class="<%= th_td_class %>">
      <%= reserve.quotation.control_unit_object_code %>
  </td>

  <td class="<%= th_td_class %>">
      <%= reserve.quantity %>
  </td>

  <td class="<%= th_td_class %>">
      <p> Estado </p>
  </td>

  <td class="<%= th_td_class %>">
    <%= reserve.user.name %>
  </td>

  <td class="<%= th_td_class %>">
    <%= render 'ventas/reserves/table_actions', reserve: reserve %>
  </td>
</tr>

app/views/ventas/reserves/edit.html.erb
<section class="bg-white dark:bg-gray-900">
  <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
    <h1 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Nueva Reserva</h1>

    <%= render "form", reserve: @reserve %>

    <div class="mt-6">
      <%= link_to "Regresar a reservas", ventas_reserves_path, class: "text-primary-700 hover:text-primary-900 dark:text-primary-500 dark:hover:text-primary-700" %>
    </div>
  </div>
</section>

app/views/ventas/reserves/index.html.erb
<section class="bg-white dark:bg-gray-900">
  <div class="py-8 px-4 mx-auto lg:py-16">
    <h1 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Reservas</h1>
    <%= link_to "Nueva reserva", new_ventas_reserve_path, class: link_index_helper %>

    <%= search_form_for @q, url: ventas_reserves_path, method: :get do |f| %>
      <% params.except(:q, :page).each do |key, value| %>
        <%= hidden_field_tag key, value %>
      <% end %>
    <% end %>
    
    <%= render(RansackSearchBarComponent.new(q: @q, url: ventas_reserves_path, field_name: :reference_number_cont, placeholder: "Buscar por No. de reserva:")) %>

    <%= render(DataTableComponent.new(headers: @headers, rows: @reserves, sort_by: @sort_by, per_page: @per_page, page: @page, pagy: @pagy, table_body_partial: 'ventas/reserves/table_body')) %>

    <script>
    document.addEventListener("turbo:load", function() {
      const url = new URL(window.location.href);
      if (!url.searchParams.has('sort_by')) {
        url.searchParams.append('sort_by', 'reference_number');
        window.history.replaceState(null, '', url);
      }
    });
    </script>

  </div>
</section>

app/views/ventas/reserves/new.html.erb
<section class="bg-white dark:bg-gray-900">
  <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
    <h1 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Nueva Reserva</h1>

    <%= render "form", reserve: @reserve %>

    <div class="mt-6">
      <%= link_to "Regresar a reservas", ventas_reserves_path, class: "text-primary-700 hover:text-primary-900 dark:text-primary-500 dark:hover:text-primary-700" %>
    </div>
  </div>
</section>

app/views/ventas/reserves/show.html.erb
<section class="bg-gray-50 dark:bg-gray-900 p-3 sm:p-5">
  <h1 class="text-6xl mb-4 text-xl font-bold text-gray-900 dark:text-white"><%= @reserve.reference_number %></h1>

  <div class="py-8 px-4 mx-auto max-w-2xl lg:py-2">

    <%= render @reserve %>

    <div class="flex items-center justify-start space-x-4 mt-6">
      <%= link_to "Editar esta reserva", edit_ventas_reserve_path(@reserve), class: "text-primary-700 hover:text-primary-900 dark:text-primary-500 dark:hover:text-primary-700" %>
      <span>|</span>
      <%= link_to "Regresar a reservas", ventas_reserves_path, class: "text-primary-700 hover:text-primary-900 dark:text-primary-500 dark:hover:text-primary-700" %>
    </div>
    <div class="mt-4">
      <%= button_to "Eliminar esta reserva", [:ventas, @reserve], method: :delete, form: { data: { turbo_confirm: '¿Estás seguro?' } }, class: "text-white bg-red-600 hover:bg-red-700 focus:ring-4 focus:ring-red-200 dark:focus:ring-red-900 font-medium rounded-lg text-sm px-5 py-2.5 text-center" %>
    </div>
  </div>
</section>