config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq-status/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  namespace :checking_account do
    resources :home, only: %i[index]
    resources :cashboxes, only: :index
    resources :consolidations, only: :index
  end

  namespace :audits do
    get "user", to: "users#index"
    get "user/:id", to: "users#show", as: "user_audit"
  end

  resources :bank_accounts
  resources :payment_methods
  resources :discount_authorizations, only: %i[index show update]

  namespace :ventas do
    resources :listado_de_precio_archivos
    resources :listado_de_precios, only: %i[index]
    resources :home, only: %i[index]
    resources :control_units, only: %i[index] do
      resources :quotations, module: "control_units"
    end
    resources :quotations, module: "control_units" do
      member do
        get "pdf", to: "quotations#pdf", as: :pdf
      end
      get "send_email_pdf/:quotation_id", to: "quotations#send_email_pdf", as: :send_email_pdf, on: :collection
    end

    get "calculator", to: "control_units/quotations#calculator", as: :calculator

    resources :reserves
  end

  resources :control_unit_types
  resources :control_unit_sub_types do
    scope module: :control_unit_sub_types do
      resources :control_unit_sub_type_projects, only: %i[index]
    end
  end
  resources :control_unit_sub_type_projects, only: %i[show update] do
    scope module: :control_unit_sub_type_projects do
      resources :extras, only: %i[index new create]
    end
  end
  resources :extras, only: %i[index show new edit create update destroy]
  get "control_unit_settings/subtypes", to: "control_unit_settings#subtypes", as: :subtypes

  resources :boundaries, only: %i[show edit update destroy]
  resources :country_settings, only: %i[index]
  resource :country_settings, only: %i[update]
  get "country_settings/subdivisions", to: "country_settings#subdivisions", as: :subdivisions
  get "country_settings/cities", to: "country_settings#cities", as: :cities
  get "projects/:project_id/control_units/export_template", to: "projects/control_units#export_template",
    as: :export_template_control_units
  resources :control_units, only: %i[show edit update destroy] do
    get "versions", on: :member
    member do
      put "boundaries", to: "control_units/boundaries#update"
    end
    collection do
      get :export_form
      post :export
    end
    resources :boundaries, shallow: true, only: %i[new index], module: :control_units
  end
  resources :projects do
    collection do
      get :export_form
      post :export
    end
    member do
      put "fincas", to: "projects/fincas#update"
    end
    resources :control_units, shallow: true, only: %i[new create index], module: :projects
    resources :fincas, shallow: true, only: %i[new index], module: :projects

    post "control_units/import_create", to: "projects/control_units#import_create", as: :import_create_control_units
    post "control_units/import_update", to: "projects/control_units#import_update", as: :import_update_control_units
  end
  resources :clients

  scope :configurations do
    # get '/', to: 'configurations#home', as: :configurations
    resources :users do
      get "versions", on: :member
    end
    resources :control_unit_statuses
    resources :roles do
      resources :permissions, shallow: true, only: %i[new create index], module: :roles
    end
    resources :financial_entities
    resources :sale_request_templates do
      get "/preview", to: "sale_request_templates#preview", as: :preview, on: :member
    end
  end
  namespace :configurations do
    resources :tipo_de_identificacion_clientes
  end
  # resources :users
  # resources :control_units do
  #   resources :boundaries
  # end
  devise_for :users, controllers: {
    sessions: "users/sessions"
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check
  root to: "home#index"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/control_unit_type.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: control_unit_types
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class ControlUnitType < ApplicationRecord
  before_save :capitalize_first_letter_of_name
  # used for handling extras
  has_many :control_unit_types_projects
  has_many :projects, through: :control_unit_types_projects
  # used for handling extras

  has_many :control_unit_sub_types

  validates :name, uniqueness: {case_sensitive: false, message: "del tipo de unidad de control ya fue ingresado"}

  def self.ransackable_attributes(_auth_object = nil)
    %w[name]
  end

  private

  def capitalize_first_letter_of_name
    self.name = name.split.map { |word| word[0].upcase + word[1..] }.join(" ")
  end
end

app/controllers/concerns/control_units.rb
# frozen_string_literal: true

# app/controllers/concerns/control_units.rb

module ControlUnits
  extend ActiveSupport::Concern

  private

  def shared_params
    [
      :project_id, :code, :description, :zero_point_location,
      :finca_number, :folio_number, :book_number, :where_is_the_book_from,
      :registered_at, :predio_number, :plan_approved_at,
      :north_location, :east_location, :altura, :area, :scale, :plan,
      :notary, :writing_date, :writing_number, :control_unit_status_id,
      :desmembración_abogado, :desmembración_fecha_de_escritura, :desmembración_número_de_escritura,
      :desmembración_quién_otorga, :desmembración_quién_recibe, :venta_abogado, :venta_fecha_de_escritura,
      :venta_número_de_escritura, :venta_quién_otorga, :venta_quién_recibe,
      :derrotero, :otro, :finca_id, :area_desmembracion, :control_unit_type_id, :control_unit_sub_type_id,
      :precio_de_lista, :precio_de_venta,
      :re_venta_abogado, :re_venta_fecha_de_escritura, :re_venta_número_de_escritura,
      :re_venta_quién_otorga, :re_venta_quién_recibe, :re_compra_abogado, :re_compra_fecha_de_escritura,
      :re_compra_número_de_escritura, :re_compra_quién_otorga, :re_compra_quién_recibe,
      :precio_de_lista_dollar, :precio_de_venta_dollar,
      {identificacion_registral: %i[
        descripcion
        numero_de_finca
        numero_de_folio
        numero_de_libro
        de_donde_es_el_libro
      ]}
    ]
  end

  def sale_detail_params
    [
      :applicant_1_id, :applicant_2_id, :applicant_1_display_text, :applicant_2_display_text, :purchase_date, :selling_price,
      :seller, :includes_deed_expenses, :currency, :construction_area, :garden_area, :parking_spaces, :balcony_area, :total_area,
      :parking_type, :estimated_delivery_date, :cash_advance, :cash_advance_interest_rate, :down_payment, :cash_advance_balance,
      :installment, :monthly_installment, :maximum_day, :finance_type, :bank, :request_number, :file, :balance, :finance_plan, :term,
      :payment_day, :monthly_payment, :annual_interest_rate, :self_financing_interest_rate, :remarks, :key1, :key2, :key3,
      :key4, :key5, :key6, :value1, :value2, :value3, :value4, :value5, :value6, :_destroy
    ]
  end

  def payment_detail_params
    [
      :user_id, :hookup, :down_payment_installment, :last_down_payment_date, :down_payment_installments, :total_installments,
      :down_payment_balance, :next_down_payment_date, :balance, :payment_method, :monthly_payment, :balance_installments,
      :start_date, :total_balance, :remarks, :_destroy, {extra_payments: %i[date receipt_number quantity client_id updated_at]},
      {down_payments: %i[date receipt_number quantity client_id updated_at]}, {late_payments: %i[date receipt_number quantity client_id updated_at]},
      {monthly_payments: %i[date receipt_number quantity late_payment interest capital others client_id updated_at]},
      {capital_payments: %i[date receipt_number quantity client_id updated_at]}, {total_payments: %i[date receipt_number quantity client_id updated_at]}
    ]
  end

  def control_unit_params_with_code_values
    new_params = params.require(:control_unit).permit(shared_params +
                                                        [control_unit_sale_detail_attributes: sale_detail_params] +
                                                        [control_unit_payment_detail_attributes: payment_detail_params])
    code_values = {}
    @project.parsed_control_unit_code_settings.each do |k, v|
      next unless v

      if k == "sufijos"
        code_values[:suffix_custom] = params[:control_unit][:suffix_custom]
        code_values[:suffix_standard] = params[:control_unit][:suffix_standard]
      end

      code_values[k] = params[:control_unit][k]
    end

    new_params[:code_values] = code_values
    new_params
  end
end

app/controllers/control_units/boundaries_controller.rb
# frozen_string_literal: true

module ControlUnits
  class BoundariesController < ApplicationController
    before_action :set_control_unit, only: %i[index new create update]

    # GET /boundaries or /boundaries.json
    def index
      @boundaries = @control_unit.boundaries
    end

    # GET /boundaries/new
    def new
      count = params[:count].to_i
      if count.zero? && @control_unit.boundaries.empty?
        redirect_back fallback_location: root_path, alert: "Se requieren al menos 1 para crear un lado del polígono"
      else
        build_boundaries(count)
      end
    end

    def update
      @control_unit_types = ControlUnitType.all.collect { |c| [c.name, c.id] }
      @control_unit_sub_types = []
      @control_unit.is_admin = current_user.admin?
      @control_unit.user_role = current_user.role_name
      respond_to do |format|
        if @control_unit.update(control_unit_params)
          if control_unit_params[:boundaries_attributes].to_h.size < @control_unit.boundaries.count
            to_destroy = Boundary.unscoped.where(control_unit_id: @control_unit.id).order(station: :desc).limit(@control_unit.boundaries.count - control_unit_params[:boundaries_attributes].to_h.size)
            to_destroy.destroy_all
            @control_unit.reload
          end
          format.html do
            redirect_to control_unit_url, notice: "La unidad de control se actualizó exitosamente."
          end
          format.json { render :show, status: :ok, location: @control_unit }
        else
          @control_unit_status = ControlUnitStatus.for_user(current_user)
          @control_unit.reload
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @control_unit.errors, status: :unprocessable_entity }
        end
      end
    end

    # POST /boundaries or /boundaries.json
    def create
    end

    # PATCH/PUT /boundaries/1 or /boundaries/1.json

    private

    def build_boundaries(count)
      if @control_unit.boundaries.empty?
        new_or_add_build_boundaries(count)
      else
        update_build_boundaries(count)
      end
    end

    def new_or_add_build_boundaries(count_or_add)
      original_count = @control_unit.boundaries.count || 0
      counter = original_count
      count = count_or_add - original_count
      count.times do |index|
        point = if index == count - 1
          0
        else
          counter + 1
        end
        @control_unit.boundaries.build(station: counter,
          observed_point: point)
        counter += 1
      end
      @control_unit.boundaries[original_count - 1].observed_point = original_count
    end

    def remove_build_boundaries(count)
      @remove_count = count
    end

    def update_build_boundaries(count)
      original_count = @control_unit.boundaries.count
      if count > original_count
        new_or_add_build_boundaries(count)
      elsif count == original_count
        nil
      else
        remove_build_boundaries(count)
      end
    end

    def set_control_unit
      id = params[:control_unit_id] || params[:id]
      @control_unit = ControlUnit.find(id)
    end

    # Only allow a list of trusted parameters through.
    def boundary_params
      params.require(:boundary).permit(:station, :observed_point, :azimuth, :distance, :neighbor, :control_units_id)
    end

    def control_unit_params
      params.require(:control_unit).permit(
        boundaries_attributes: %i[id station observed_point azimuth distance
          neighbor control_unit_id _destroy]
      )
    end
  end
end

app/helpers/control_units_helper.rb
# frozen_string_literal: true

module ControlUnitsHelper
  def format_decimal(area)
    return nil if area.blank?

    format("%.2f", area)
  end

  def format_decimal_fincas(area)
    return nil if area.blank?

    format("%.4f", area)
  end

  def text_field_class_cu_code
    "p-2.5 text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 w-20"
  end

  def text_field_class_cu_suffix
    "p-2.5 text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 w-10"
  end

  def div_control_unit_edit_class
    "py-8 px-4 mx-auto max-w-3xl lg:py-2"
  end

  def form_control_unit_class
    "bg-white dark:bg-gray-900 py-8 px-4 mx-auto lg:py-2"
  end

  def custom_text_field_cu(form, field, options = {})
    form.text_field field, options
  end

  def custom_select_cu(form, field, collection, options = {}, html_options = {})
    form.select field, collection, options, html_options
  end

  def datepicker_field_cu(form, field, options = {})
    disabled = false
    options[:class] =
      "#{options[:class]} #{if disabled
                              "cursor-not-allowed"
                            end} bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
    options[:disabled] = disabled

    # Configuración específica del datepicker
    datepicker_options = {
      datepicker: true,
      "datepicker-format": "dd/mm/yyyy",
      placeholder: "Selecciona una fecha"
    }

    # Combinar opciones específicas del datepicker con las opciones proporcionadas
    combined_options = options.merge(datepicker_options)

    # Formatear la fecha si el objeto tiene un valor para ese campo
    formatted_date = form.object.send(field)&.strftime("%d/%m/%Y")
    combined_options[:value] = formatted_date if formatted_date

    # Crear el campo de texto con las opciones combinadas
    content_tag(:div, class: "relative max-w-sm") do
      icon = content_tag(:div, class: "absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none") do
        # Icono de calendario (puedes ajustar esto según tus necesidades)
        tag.svg(class: "w-5 h-5 text-gray-500", xmlns: "http://www.w3.org/2000/svg", fill: "none", viewBox: "0 0 24 24",
          stroke: "currentColor") do
          tag.path(stroke_linecap: "round", stroke_linejoin: "round", stroke_width: "2",
            d: "M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z").to_s.html_safe
        end
      end

      # Combina el icono y el input
      icon + form.text_field(field, combined_options)
    end
  end

  def custom_control_data_attribute(group)
    unless current_user.role.name == "Admin" || current_user.role.permissions.where(subject_class: "CustomControlUnitGroup")
        .pluck(:action).include?(group)
      "data-controller=control-units--custom-group"
    end
  end
end

app/views/ventas/control_units/quotations/_table_actions.html.erb
<div class="flex space-x-2">
  <%= link_to ventas_quotation_url(quotation), data: { turbo_frame: "_top" } do %>
    <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
      <path stroke="currentColor" stroke-width="2" d="M21 12c0 1.2-4 6-9 6s-9-4.8-9-6c0-1.2 4-6 9-6s9 4.8 9 6Z"/>
      <path stroke="currentColor" stroke-width="2" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
    </svg>
  <% end %>

  <%= link_to edit_ventas_quotation_url(quotation), data: { turbo_frame: "_top" } do %>
    <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m10.8 17.8-6.4 2.1 2.1-6.4m4.3 4.3L19 9a3 3 0 0 0-4-4l-8.4 8.6m4.3 4.3-4.3-4.3m2.1 2.1L15 9.1m-2.1-2 4.2 4.2"/>
    </svg>
  <% end %>

  <%= link_to "#{ventas_quotation_url(quotation)}/pdf.pdf", target: "_blank" do %>
    <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
      <path stroke="currentColor" stroke-linejoin="round" stroke-width="2" d="M16.444 18H19a1 1 0 0 0 1-1v-5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h2.556M17 11V5a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v6h10ZM7 15h10v4a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1v-4Z"/>
    </svg>
  <% end %>

  <%= link_to "#{send_email_pdf_ventas_quotations_url(quotation)}" do %>
    <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
      <path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="m3.5 5.5 7.893 6.036a1 1 0 0 0 1.214 0L20.5 5.5M4 19h16a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1Z"/>
    </svg>
  <% end %>

  <%= button_to ventas_quotation_url(quotation), method: :delete, form: { data: { turbo: false, controller: "confirm", confirm_message_value: "¿Estás seguro?" }} do %>
    <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 7h14m-9 3v8m4-8v8M10 3h4a1 1 0 0 1 1 1v3H9V4a1 1 0 0 1 1-1ZM6 7h12v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7Z"/>
    </svg>
  <% end %>
</div>

app/views/ventas/control_units/quotations/_table_body.html.erb
<%
  quotation = row

  discount_auth = quotation.discount_authorization

  if discount_auth.present?
    font_color = case discount_auth.status
      when 'pending'    then 'text-amber-500'
      when 'approved'   then 'text-green-500'
      when 'unapproved' then 'text-red-500'
    end
  end
%>

<tr class="<%= tr_class %>">
  <td class="<%= th_td_class %>">
    <%= link_to ventas_quotation_url(quotation),
                data: { turbo_frame: "_top" },
                target: "_blank",
                class: font_color do %>
      <%= quotation.reference_number %>
    <% end %>
  </td>

  <td class="<%= th_td_class %>">
    <%= quotation.client_name %>
  </td>

  <td class="<%= th_td_class %>">
    <%= l(quotation.created_at, format: :short) %>
  </td>

  <td class="<%= th_td_class %>">
    <%= l(quotation.updated_at, format: :short) %>
  </td>

  <td class="<%= th_td_class %>">
    <%= render 'ventas/control_units/quotations/table_actions', quotation: quotation %>
  </td>
</tr>

app/views/ventas/control_units/quotations/edit.html.erb
<section class="bg-white dark:bg-gray-900">
  <div class="py-8 px-4 mx-auto max-w-7xl lg:py-16">
  <h1 class="<%= h1_edit_class %>">Cotización de unidades de control: <%= @quotation.reference_number %></h1>

  <%= render "form" , quotation: @quotation %>

    <br>

    <div class="<%= div_links_edit_class %>">
      <%= link_to "Mostrar esta cotización" , ventas_quotation_url(@quotation), class: link_edit_class %>
      <span>|</span>
      <%= link_to "Regresar a cotizaciones" , ventas_quotations_path, class: link_edit_class %>
    </div>
  </div>
</section>

app/views/ventas/control_units/quotations/index.html.erb
<section class="bg-white dark:bg-gray-900">
  <div class="py-8 px-4 mx-auto lg:py-16">
    <h1 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Cotizaciones</h1>

    <%= render(RansackSearchBarComponent.new(q: @q, url: ventas_quotations_path, field_name: :client_name_or_reference_number_cont, placeholder: "Nombre de cliente o número de cotización contiene:")) %>
    <%= render(DataTableComponent.new(headers: @headers, rows: @quotations, sort_by: @sort_by, per_page: @per_page, page: @page, pagy: @pagy, table_body_partial: 'ventas/control_units/quotations/table_body', actions: true) ) %>
    </div>
</section>

app/views/ventas/control_units/quotations/show.html.erb
<section class="bg-gray-50 dark:bg-gray-900 p-3 sm:p-5">
  <div class="w-full flex flex-row align-middle justify-between">
    <h1 class="<%= h1_edit_class %>">Cotización de unidades de control: <%= @quotation.reference_number %></h1>
    <div class="flex flex-row">
      <%= link_to "#{send_email_pdf_ventas_quotations_url(@quotation)}",
              class: "inline-flex items-center ml-3 text-white bg-cyan-700 hover:bg-cyan-800 focus:ring-4 focus:outline-none focus:ring-cyan-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-cyan-600 dark:hover:bg-cyan-700 dark:focus:ring-cyan-800" do %>
        <svg class="w-6 h-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16">
          <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z"/>
        </svg>
        <span class="ml-1">Enviar</span>
      <% end %>

      <%= link_to "#{ventas_quotation_url(@quotation)}/pdf.pdf", target: "_blank",
              class: "inline-flex items-center ml-3 text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-800" do %>
        <svg class="w-6 h-6 text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linejoin="round" stroke-width="2" d="M16.444 18H19a1 1 0 0 0 1-1v-5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h2.556M17 11V5a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v6h10ZM7 15h10v4a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1v-4Z"/>
        </svg>
        <span class="ml-1">Descargar</span>
      <% end %>

      <%= link_to "", 
              class: "inline-flex items-center ml-3 text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800" do %>
        <svg class="w-6 h-6 text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 10h16m-8-3V4M7 7V4m10 3V4M5 20h14a1 1 0 0 0 1-1V7a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1Zm3-7h.01v.01H8V13Zm4 0h.01v.01H12V13Zm4 0h.01v.01H16V13Zm-8 4h.01v.01H8V17Zm4 0h.01v.01H12V17Zm4 0h.01v.01H16V17Z"/>
        </svg>
        <span class="ml-1">Reservar</span>
      <% end %>
      
      <%= link_to "", 
              class: "inline-flex items-center ml-3 text-white bg-gray-700 hover:bg-gray-800 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800" do %>
        <svg class="w-6 h-6 text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.5 11.5 11 14l4-4m6 2a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
        </svg>
        <span class="ml-1">Comprar</span>
      <% end %>
    </div>
  </div>

  <div class="py-8 px-4 mx-auto max-w-7xl lg:py-2">

    <%= render @quotation %>

    <div class="flex items-center justify-start space-x-4 mt-6">
      <%= link_to "Editar esta cotización", edit_ventas_quotation_path(@quotation), class: "text-primary-700 hover:text-primary-900 dark:text-primary-500 dark:hover:text-primary-700" %>
      <span>|</span>
      <%= link_to "Regresar a cotizaciones", ventas_quotations_path, class: "text-primary-700 hover:text-primary-900 dark:text-primary-500 dark:hover:text-primary-700" %>
    </div>
    <div class="mt-4">
      <%= button_to "Eliminar esta cotización", ventas_quotation_url(@quotation), method: :delete, form: { data: { turbo: false, controller: "confirm", confirm_message_value: "¿Estás seguro?" }}, class: "text-white bg-red-600 hover:bg-red-700 focus:ring-4 focus:ring-red-200 dark:focus:ring-red-900 font-medium rounded-lg text-sm px-5 py-2.5 text-center" %>
    </div>

    <div class="flex items-center justify-start space-x-4 mt-6">
    </div>
  </div>
</section>