config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq-status/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  namespace :checking_account do
    resources :home, only: %i[index]
    resources :cashboxes, only: :index
    resources :consolidations, only: :index
  end

  namespace :audits do
    get "user", to: "users#index"
    get "user/:id", to: "users#show", as: "user_audit"
  end

  resources :bank_accounts
  resources :payment_methods
  resources :discount_authorizations, only: %i[index show update]

  namespace :ventas do
    resources :listado_de_precio_archivos
    resources :listado_de_precios, only: %i[index]
    resources :home, only: %i[index]
    resources :control_units, only: %i[index] do
      resources :quotations, module: "control_units"
    end
    resources :quotations, module: "control_units" do
      member do
        get "pdf", to: "quotations#pdf", as: :pdf
      end
      get "send_email_pdf/:quotation_id", to: "quotations#send_email_pdf", as: :send_email_pdf, on: :collection
    end

    get "calculator", to: "control_units/quotations#calculator", as: :calculator

    resources :reserves
  end

  resources :control_unit_types
  resources :control_unit_sub_types do
    scope module: :control_unit_sub_types do
      resources :control_unit_sub_type_projects, only: %i[index]
    end
  end
  resources :control_unit_sub_type_projects, only: %i[show update] do
    scope module: :control_unit_sub_type_projects do
      resources :extras, only: %i[index new create]
    end
  end
  resources :extras, only: %i[index show new edit create update destroy]
  get "control_unit_settings/subtypes", to: "control_unit_settings#subtypes", as: :subtypes

  resources :boundaries, only: %i[show edit update destroy]
  resources :country_settings, only: %i[index]
  resource :country_settings, only: %i[update]
  get "country_settings/subdivisions", to: "country_settings#subdivisions", as: :subdivisions
  get "country_settings/cities", to: "country_settings#cities", as: :cities
  get "projects/:project_id/control_units/export_template", to: "projects/control_units#export_template",
    as: :export_template_control_units
  resources :control_units, only: %i[show edit update destroy] do
    get "versions", on: :member
    member do
      put "boundaries", to: "control_units/boundaries#update"
    end
    collection do
      get :export_form
      post :export
    end
    resources :boundaries, shallow: true, only: %i[new index], module: :control_units
  end
  resources :projects do
    collection do
      get :export_form
      post :export
    end
    member do
      put "fincas", to: "projects/fincas#update"
    end
    resources :control_units, shallow: true, only: %i[new create index], module: :projects
    resources :fincas, shallow: true, only: %i[new index], module: :projects

    post "control_units/import_create", to: "projects/control_units#import_create", as: :import_create_control_units
    post "control_units/import_update", to: "projects/control_units#import_update", as: :import_update_control_units
  end
  resources :clients

  scope :configurations do
    # get '/', to: 'configurations#home', as: :configurations
    resources :users do
      get "versions", on: :member
    end
    resources :control_unit_statuses
    resources :roles do
      resources :permissions, shallow: true, only: %i[new create index], module: :roles
    end
    resources :financial_entities
    resources :sale_request_templates do
      get "/preview", to: "sale_request_templates#preview", as: :preview, on: :member
    end
  end
  namespace :configurations do
    resources :tipo_de_identificacion_clientes
  end
  # resources :users
  # resources :control_units do
  #   resources :boundaries
  # end
  devise_for :users, controllers: {
    sessions: "users/sessions"
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check
  root to: "home#index"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/discount_authorization.rb
# == Schema Information
#
# Table name: discount_authorizations
#
#  id               :bigint           not null, primary key
#  approval_date    :datetime
#  approval_reason  :string
#  comment          :string
#  discount_value   :integer
#  sale_value       :integer
#  status           :integer          default("pending")
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  approval_user_id :integer
#  quotation_id     :bigint           not null
#
# Indexes
#
#  index_discount_authorizations_on_quotation_id  (quotation_id)
#
# Foreign Keys
#
#  fk_rails_...  (quotation_id => quotations.id)
#
class DiscountAuthorization < ApplicationRecord
  belongs_to :quotation
  belongs_to :approval_user, class_name: "User", optional: true
  validates :comment, presence: true

  enum status: {pending: 0, approved: 1, unapproved: 2}

  after_update :update_quotation_discount_status

  delegate :currency, to: :quotation
  delegate :last_edited_by_name, to: :quotation
  delegate :reference_number, to: :quotation, prefix: true

  def pending?
    status == "pending"
  end

  def approved?
    status == "approved"
  end

  def unapproved?
    status == "unapproved"
  end

  def translated_status
    I18n.t("activerecord.attributes.discount_authorization.statuses.#{status}")
  end

  private

  def update_quotation_discount_status
    quotation_params = quotation.parsed_params
    quotation_params["discount_status"] = status
    quotation.update(quotation_params: quotation_params.to_json)
  end
end

app/controllers/discount_authorizations_controller.rb
class DiscountAuthorizationsController < ApplicationController
  before_action :set_discount_authorization, only: %i[show update]
  before_action :set_query_params, only: %i[index]

  def index
    @headers = [
      {name: "No. de Cotización", field: "quotation_reference_number", sortable: true},
      {name: "Precio", field: "sale_value"},
      {name: "Descuento", field: "discount_value", sortable: true},
      {name: "Vendedor", field: "last_edited_by_name"},
      {name: "Estado", field: "status", sortable: true}
    ]

    discount_authorizations = DiscountAuthorization.joins(:quotation)
      .select("discount_authorizations.*, quotations.reference_number AS quotation_reference_number")

    @pagy, @discount_authorizations = process_query_params(discount_authorizations)
  end

  def show
  end

  def update
    new_params = discount_authorization_params.merge(approval_user_id: current_user.id, approval_date: Time.zone.now)

    if @discount_authorization.update(new_params)
      redirect_to discount_authorization_path(@discount_authorization), notice: "La autorización de descuento ha sido actualizada exitosamente."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_discount_authorization
    @discount_authorization = DiscountAuthorization.find(params[:id])
  end

  def discount_authorization_params
    params.require(:discount_authorization).permit(:approval_reason, :status)
  end
end

app/views/discount_authorizations/_approve_discount_modal.html.erb
<form method="patch" class="local">
  <div class="p-6 space-y-6">
    <div>
      <label for="discount_authorization_approval_reason" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Razón:</label>
      <textarea id="discount_authorization_approval_reason" name="discount_authorization[approval_reason]" class="block w-full p-2.5 text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" rows="2"></textarea>
    </div>
  </div>
  <div
    class="flex justify-between space-x-2 p-6 rtl:space-x-reverse rounded-b">
    <button
      type="button"
      class="rounded-lg bg-red-700 px-5 py-2.5 text-center text-sm font-medium text-white hover:bg-red-800 focus:outline-none focus:ring-4 focus:ring-red-300 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800"
      data-modal-hide="<%= modal_id %>">
      Cancelar
    </button>
    <button
      type="submit"
      class="inline-flex items-center rounded-lg bg-blue-700 px-5 py-2.5 text-center text-sm font-medium text-white hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
    >
      Enviar
      <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9" />
      </svg>
    </button>
  </div>
</form>

app/views/discount_authorizations/_discount_authorization.html.erb
<div id="<%= dom_id(discount_authorization) %>" class="<%= form_details_class %>">
  <h1 class="mb-2 text-lg font-bold text-gray-900 dark:text-white">Solicitud de Descuento</h1>
  <p class="<%= p_class %>">
    <strong>Número de Cotización:</strong>
    <%= discount_authorization.quotation_reference_number %>
  </p>
  <p class="<%= p_class %>">
    <strong>Precio:</strong>
    <%= currency_of(discount_authorization.sale_value, discount_authorization.currency) %>
  </p>
  <p class="<%= p_class %>">
    <strong>Descuento:</strong>
    <%= currency_of(discount_authorization.discount_value, discount_authorization.currency) %>
  </p>
  <p class="<%= p_class %>">
    <strong>Vendedor:</strong>
    <%= discount_authorization.last_edited_by_name %>
  </p>
  <%
    bg_color = case discount_authorization.status
               when 'pending' then 'bg-amber-500'
               when 'approved' then 'bg-green-500'
               when 'unapproved' then 'bg-red-500'
               end
  %>
  <p class="<%= p_class %>">
    <strong>Estado:</strong>
    <span class="w-auto aspect-square <%= bg_color %> text-white p-1 rounded-lg"><%= discount_authorization.translated_status %></span>
  </p>
  <p class="<%= p_class %>">
    <strong>Comentario:</strong>
    <%= discount_authorization.comment %>
  </p>

  <h1 class="mt-6 mb-2 text-lg font-bold text-gray-900 dark:text-white">Estatus Final</h1>
  <p class="<%= p_class %>">
    <strong>Revisado Por:</strong>
    <%= discount_authorization.approval_user.name if discount_authorization.approval_user %>
  </p>
  <p class="<%= p_class %>">
    <strong>Razón:</strong>
    <%= discount_authorization.approval_reason %>
  </p>
  <p class="<%= p_class %>">
    <strong>Fecha:</strong>
    <%= l(discount_authorization.approval_date, format: :short) if discount_authorization.approval_date %>
  </p>
</div>

app/views/discount_authorizations/_table_body.html.erb
<%
  discount_authorization = row
  bg_color = case discount_authorization.status
    when 'pending' then 'bg-amber-500'
    when 'approved' then 'bg-green-500'
    when 'unapproved' then 'bg-red-500'
  end
  font_color = case discount_authorization.status
    when 'pending'    then 'text-amber-500'
    when 'approved'   then 'text-green-500'
    when 'unapproved' then 'text-red-500'
  end
%>
<tr class="<%= tr_class %>" >
  <td class="<%= th_td_class %>">
    <%= link_to ventas_quotation_url(discount_authorization.quotation), data: { turbo_frame: "_top" }, target: "_blank", class: font_color do %>
      <%= discount_authorization.quotation_reference_number %>
    <% end %>
  </td>
  <td class="<%= th_td_class %>">
    <%= currency_of(discount_authorization.sale_value, discount_authorization.currency) %>
  </td>
  <td class="<%= th_td_class %>">
    <%= currency_of(discount_authorization.discount_value, discount_authorization.currency) %>
  </td>
  <td class="<%= th_td_class %>">
    <%= discount_authorization.quotation.last_edited_by_name %>
  </td>
  <td class="<%= th_td_class %>">
    <span class="w-auto aspect-square <%= bg_color %> text-white p-1 rounded-lg"><%= discount_authorization.translated_status %></span>
  </td>
  <td class="<%= th_td_class %> flex">
    <%= link_to discount_authorization_url(discount_authorization), data: { turbo_frame: "_top" } do %>
      <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
        <path stroke="currentColor" stroke-width="2" d="M21 12c0 1.2-4 6-9 6s-9-4.8-9-6c0-1.2 4-6 9-6s9 4.8 9 6Z"/>
        <path stroke="currentColor" stroke-width="2" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
      </svg>
    <% end %>
    <% if discount_authorization.pending? %>
      <div data-modal-show="approve_discount"
           data-action="click->discount-authorizations#approve"
           data-update-url="<%= discount_authorization_path(discount_authorization) %>"
           data-discount-authorizations-target="approveButton">
        <svg class="w-6 h-6 text-gray-800 dark:text-white cursor-pointer" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 11c.889-.086 1.416-.543 2.156-1.057a22.323 22.323 0 0 0 3.958-5.084 1.6 1.6 0 0 1 .582-.628 1.549 1.549 0 0 1 1.466-.087c.205.095.388.233.537.406a1.64 1.64 0 0 1 .384 1.279l-1.388 4.114M7 11H4v6.5A1.5 1.5 0 0 0 5.5 19v0A1.5 1.5 0 0 0 7 17.5V11Zm6.5-1h4.915c.286 0 .372.014.626.15.254.135.472.332.637.572a1.874 1.874 0 0 1 .215 1.673l-2.098 6.4C17.538 19.52 17.368 20 16.12 20c-2.303 0-4.79-.943-6.67-1.475"/>
        </svg>
      </div>
      <div data-modal-show="unapprove_discount"
            data-action="click->discount-authorizations#unapprove"
            data-update-url="<%= discount_authorization_path(discount_authorization) %>"
            data-discount-authorizations-target="unapproveButton">
        <svg class="w-6 h-6 text-gray-800 dark:text-white cursor-pointer" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 13c-.889.086-1.416.543-2.156 1.057a22.322 22.322 0 0 0-3.958 5.084 1.6 1.6 0 0 1-.582.628 1.549 1.549 0 0 1-1.466.087 1.587 1.587 0 0 1-.537-.406 1.666 1.666 0 0 1-.384-1.279l1.389-4.114M17 13h3V6.5A1.5 1.5 0 0 0 18.5 5v0A1.5 1.5 0 0 0 17 6.5V13Zm-6.5 1H5.585c-.286 0-.372-.014-.626-.15a1.797 1.797 0 0 1-.637-.572 1.873 1.873 0 0 1-.215-1.673l2.098-6.4C6.462 4.48 6.632 4 7.88 4c2.302 0 4.79.943 6.67 1.475"/>
        </svg>
      </div>
    <% end %>
  </td>
</tr>

app/views/discount_authorizations/index.html.erb
<section class="bg-white dark:bg-gray-900" data-controller="discount-authorizations">
  <div class="py-8 px-4 mx-auto lg:py-16">
    <h1 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Autorizaciones de descuento</h1>

    <%= render(DataTableComponent.new(headers: @headers, rows: @discount_authorizations, sort_by: @sort_by, per_page: @per_page, page: @page, pagy: @pagy, table_body_partial: 'discount_authorizations/table_body', actions: true)) %>
    <%= render(ModalComponent.new(title: "Aprobar Descuento", partial: "discount_authorizations/approve_discount_modal", modal_id: "approve_discount", locals: { modal_id: "approve_discount", new_status: "approved" })) %>
    <%= render(ModalComponent.new(title: "Rechazar Descuento", partial: "discount_authorizations/approve_discount_modal", modal_id: "unapprove_discount", locals: { modal_id: "unapprove_discount", new_status: "unapproved" })) %>
  </div>
</section>

app/views/discount_authorizations/show.html.erb
<section class="bg-gray-50 dark:bg-gray-900 p-3 sm:p-5">
  <h1 class="text-6xl mb-4 text-xl font-bold text-gray-900 dark:text-white">Autorización de Descuento</h1>

  <div class="py-8 px-4 mx-auto max-w-2xl lg:py-2">

    <%= render @discount_authorization %>

    <div class="flex items-center justify-start space-x-4 mt-6">
      <%= link_to "Regresar a autorización de descuentos", discount_authorizations_path, class: "text-primary-700 hover:text-primary-900 dark:text-primary-500 dark:hover:text-primary-700" %>
    </div>
  </div>
</section>